[package]
name = "aml_tester"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"

[dependencies]
clap = "4"
termion = "1"
log = "0.4"
aml = { path = "../aml" }
toml = "0.8.13"
serde = { version = "1.0", features = ["derive"] }
